java -jar asg1jarfile.jar ../inputs/input1.txt output1.txt
java -jar asg1jarfile.jar ../inputs/input2.txt output2.txt
java -jar asg1jarfile.jar ../inputs/input3.txt output3.txt
java -jar asg1jarfile.jar ../inputs/input4.txt output4.txt
java -jar asg1jarfile.jar ../inputs/input5.txt output5.txt
java -jar asg1jarfile.jar ../inputs/input6.txt output6.txt
java -jar asg1jarfile.jar ../inputs/input7.txt output7.txt
java -jar asg1jarfile.jar ../inputs/input8.txt output8.txt
java -jar asg1jarfile.jar ../inputs/input9.txt output9.txt
java -jar asg1jarfile.jar ../inputs/InvalidForbidMach.txt InvalidForbidMachOutput.txt
java -jar asg1jarfile.jar ../inputs/InvalidForcedPartAsg.txt InvalidForcedPartAsgOutput.txt
java -jar asg1jarfile.jar ../inputs/InvalidInForbidMach.txt InvalidForbiddenMachOutput.txt
java -jar asg1jarfile.jar ../inputs/InvalidMachPenal.txt InvalidMachPenalOutput.txt
java -jar asg1jarfile.jar ../inputs/InvalidMachPenalNotEnough.txt InvalidMachPenalNotEnoughOutput.txt
java -jar asg1jarfile.jar ../inputs/InvalidPartAsg2.txt InvalidPartAsg2Output.txt
java -jar asg1jarfile.jar ../inputs/InvalidTooNearPenal.txt IInvalidTooNearPenalOutput.txt
java -jar asg1jarfile.jar ../inputs/NineForcedPartAsg.txt NineForcedPartAsgOutput.txt
#java -jar asg1jarfile.jar ../inputs/ComplexInvalidTest.txt ComplexInvalidTestutput.txt
