#java -jar newnopckgjar.jar ../inputs/input1.txt output1.txt
#java -jar newnopckgjar.jar ../inputs/input2.txt output2.txt
#java -jar newnopckgjar.jar ../inputs/input3.txt output3.txt
#java -jar newnopckgjar.jar ../inputs/input4.txt output4.txt
#java -jar newnopckgjar.jar ../inputs/input5.txt output5.txt
#java -jar newnopckgjar.jar ../inputs/input6.txt output6.txt
#java -jar newnopckgjar.jar ../inputs/input7.txt output7.txt
#java -jar newnopckgjar.jar ../inputs/input8.txt output8.txt
#java -jar newnopckgjar.jar ../inputs/input9.txt output9.txt
#java -jar newnopckgjar.jar ../inputs/InvalidForbidMach.txt InvalidForbidMachOutput.txt
#java -jar newnopckgjar.jar ../inputs/InvalidForcedPartAsg.txt InvalidForcedPartAsgOutput.txt
#java -jar newnopckgjar.jar ../inputs/InvalidInForbidMach.txt InvalidForbiddenMachOutput.txt
#java -jar newnopckgjar.jar ../inputs/InvalidMachPenal.txt InvalidMachPenalOutput.txt
#java -jar newnopckgjar.jar ../inputs/InvalidMachPenalNotEnough.txt InvalidMachPenalNotEnoughOutput.txt
#java -jar newnopckgjar.jar ../inputs/InvalidPartAsg2.txt InvalidPartAsg2Output.txt
#java -jar newnopckgjar.jar ../inputs/InvalidTooNearPenal.txt IInvalidTooNearPenalOutput.txt
#java -jar newnopckgjar.jar ../inputs/NineForcedPartAsg.txt NineForcedPartAsgOutput.txt
#java -jar newnopckgjar.jar ../inputs/ComplexInvalidTest.txt ComplexInvalidTestutput.txt
java -jar newnopckgjar.jar ../inputs/invalid2.txt invalid2output.txt
java -jar newnopckgjar.jar ../inputs/invalidforbidden.txt invalidforbiddenoutput.txt
java -jar newnopckgjar.jar ../inputs/invalidtoonear.txt invalidtoonearoutput.txt
java -jar newnopckgjar.jar ../inputs/machpen1.txt machpen1output.txt
java -jar newnopckgjar.jar ../inputs/machpen2.txt machpen2output.txt
java -jar newnopckgjar.jar ../inputs/nochoice.txt nochoiceoutput.txt
java -jar newnopckgjar.jar ../inputs/nochoice2.txt nochoice2output.txt
java -jar newnopckgjar.jar ../inputs/optzero.txt optzerooutput.txt
java -jar newnopckgjar.jar ../inputs/toonearpen1.txt toonearpen1output.txt
java -jar newnopckgjar.jar ../inputs/toonearpen2.txt toonearpen2output.txt
java -jar newnopckgjar.jar ../inputs/wrongmachine.txt wrongmachineoutput.txt
java -jar newnopckgjar.jar ../inputs/wrongnumbermachine.txt wrongnumbermachineoutput.txt
java -jar newnopckgjar.jar ../inputs/wrongnumbertoonear.txt wrongnumbertoonearoutput.txt
java -jar newnopckgjar.jar ../inputs/wrongtooneartask.txt wrongtooneartaskoutput.txt


